# Generated by Django 3.2.7 on 2021-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(choices=[('India', 'IN'), ('US', 'USA')], max_length=256)),
            ],
        ),
    ]
